package by.epam.onlinetraining.command;

public enum ActionCommandType {
    LOGIN,
    LOGOUT,
    SIGNUP,
    LOCALE,
    SHOWAVAILABLECOURSES,
    JOINCOURSE,
    SHOWTAKENCOURSES,
    SHOWRECEIVEDTASKS,
    SENDANSWER,
    SHOWALLTEACHERS,
    SHOWALLCOURSES,
    ADDCOURSE,
    ADDTEACHER,
    DELETEUSER,
    EDITCOURSE,
    SHOWTEACHERRELATEDCOURSES,
    SHOWCOURSERELATEDTASKS,
    SHOWREVIEWSBYTASKID,
    SENDREVIEW,
    GETPAGE,
    ADDTASK,
    RECOVERPASSWORD,
    GETSTATISTICS
}
