package by.epam.onlinetraining.command;

public enum CommandType {
    LOGIN,
    LOGOUT,
    SIGNUP,
    LOCALE,
    TAKEAVAILABLECOURSES,
    JOINCOURSE,
    GETTAKENCOURSES,
    TAKERECEIVEDTASKS,
    SENDANSWER,
    TAKEALLTEACHERS,
    TAKEALLCOURSES,
    ADDCOURSE,
    ADDTEACHER,
    DELETEUSER,
    EDITCOURSE,
    TAKETEACHERRELATEDCOURSES,
    TAKECOURSERELATEDTASKS,
    TAKEREVIEWSBYTASKID,
    SENDREVIEW,
    GETPAGE,
    ADDTASK,
    RECOVERPASSWORD,
    GETSTATISTICS
}
