-- Users
INSERT INTO `onlinetraining`.`users` (`user_email`, `user_password`, `first_name`, `last_name`, `user_role`, `user_isDeleted`)
VALUES
('adnorthon@example.com', '2939094f35a3badf2a890768ba034fa5eb16e95e', 'Advard', 'Northon', 'admin', '0'),
('ivanov@example.com', '5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8', 'Ivan', 'Ivanov', 'teacher', '0'),
('petrov@example.com', '5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8', 'Petr', 'Petrov', 'teacher', '0'),
('sidorov@example.com', '5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8', 'Alex', 'Sidorov', 'teacher', '0'),
('pavlenchuk@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Pavel', 'Pavlencuk', 'student', '0'),
('putin@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Vladimir', 'Putin', 'student', '0'),
('sokol@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Vladislav', 'Sakolik', 'student', '0'),
('tihaya@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Alesya', 'Tihaya', 'student', '0'),
('pavlova@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Vlada', 'Pavlova', 'student', '0'),
('tumen@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Aleksandra', 'Tumen', 'student', '0'),
('savchenko@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Petr', 'Savchenko', 'student', '0'),
('glebov@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Artem', 'Glebov', 'student', '0'),
('zabugornaya@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Sabrina', 'Zabugornaya', 'student', '0'),
('rus@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Vera', 'Russkaya', 'student', '0'),
('self@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Dasha', 'Kakayuaest', 'student', '0'),
('same@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Masha', 'Toje', 'student', '0'),
('bondarchuk@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Genadiy', 'Bondarchuk', 'student', '0'),
('kravchenko@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Valentin', 'Kravchenko', 'student', '0'),
('menishov@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Oleg', 'Menishov', 'student', '0'),
('mstislavec@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Fedor', 'Mstislavec', 'student', '0'),
('sobolev@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Marshal', 'Sobolev', 'student', '0'),
('kirilenko@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Oleg', 'Kirilenko', 'student', '0'),
('kolovrat@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Ivan', 'Drujko', 'student', '0'),
('kami@example.com', '45f106ef4d5161e7aa38cf6c666607f25748b6ca', 'Dmitriy', 'Morozov', 'student', '0');

-- Subjects
INSERT INTO `onlinetraining`.`subjects` (`subject_language`, `subject_level`)
VALUES
('english', 'A1'),
('english', 'A2'),
('english', 'B1'),
('english', 'B2'),
('english', 'C1'),
('english', 'C2'),
('german', 'A1'),
('german', 'A2'),
('german', 'B1'),
('german', 'B2'),
('german', 'C1'),
('german', 'C2'),
('french', 'A1'),
('french', 'A2'),
('french', 'B1'),
('french', 'B2'),
('french', 'C1'),
('french', 'C2'),
('italian', 'A1'),
('italian', 'A2'),
('italian', 'B1'),
('italian', 'B2'),
('italian', 'C1'),
('italian', 'C2'),
('spanish', 'A1'),
('spanish', 'A2'),
('spanish', 'B1'),
('spanish', 'B2'),
('spanish', 'C1'),
('spanish', 'C2');

-- Courses
INSERT INTO `onlinetraining`.`courses` (`course_title`, `course_subject_id`, `course_status`, `course_isAvailable`, `course_teacher_id`)
VALUES
('English for beginers', 1, 'running', 0, 2),
('English for advanced', 5, 'running', 1, 2),
('German for beginers', 8, 'gathering', 1, 3),
('French for expirienced', 9, 'running', 1, 4),
('English for expirienced', 4, 'gathering', 1, 2);

-- Tasks
INSERT INTO `onlinetraining`.`tasks` (`task_name`, `task_description`, `task_course_id`)
VALUES
('First beginers English task', 'Write down 10 English words you just learned', 1),
('First advanced English task', 'Write a text on English. Minimal text length is 1000 words.', 2),
('First French task', 'Write down 10 french words you just learned', 4),
('Second advanced English task', 'Write a poem on English. Minimal text length is 100 words.', 2);

-- Courses_has_students
INSERT INTO `onlinetraining`.`courses_has_students`(courses_course_id, users_user_id)
VALUES
(1,5),
(1,6),
(1,7),
(1,8),
(1,9),
(1,10),
(2,11),
(2,12),
(2,13),
(2,14),
(2,15),
(3,16),
(3,17),
(4,18),
(4,19),
(4,20),
(4,21),
(5,22),
(5,23),
(5,24);

-- Students_has_tasks
INSERT INTO `onlinetraining`.`students_has_tasks`(`users_user_id`, `tasks_task_id`, `task_answer`, `task_mark`, `task_review`)
VALUES
(5, 1,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
7, 'not bad'),
(6, 1,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
5, 'try harder'),
(7, 1,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
9, 'excellent'),
(8, 1,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
6, 'not bad'),
(9, 1,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
4, 'pathetic'),
(10, 1,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
7, 'not bad'),
(11, 2,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
5, 'try harder'),
(12, 2,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
7, 'not bad'),
(13, 2,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
8, 'good enough'),
(14, 2,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
10, 'excellent'),
(15, 2,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
7, 'not bad'),
(18, 3,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
8, 'good enough'),
(19, 3,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
9, 'excellent'),
(20, 3,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
7, 'not bad'),
(21, 3,
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia pulvinar aliquam. Nam nunc nibh, interdum non iaculis at, scelerisque non mi. Integer facilisis eros risus, mattis efficitur nibh malesuada eget. In ultricies turpis eu tellus hendrerit euismod. Fusce lacinia quis enim ut cursus. Proin et arcu ac sapien feugiat dictum non id ipsum. Nullam finibus luctus turpis. Aliquam tincidunt.',
6, 'not bad'),
(5, 4, null, null, null),
(6, 4, null, null, null),
(7, 4, null, null, null),
(8, 4, null, null, null),
(9, 4, null, null, null);